# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc708bbbf35d4ec006c008cc6e62741f62cb176b1e85b0a1fac4bb7bd9f01137cb309dcc5d58e4ae675754cf14693bb8c775562e90c15d90d46a8861b6c5707

test:
  secret_key_base: 6494107037703199e933a60530dcab10acf52e878d728b520669010b4d107067d124abeffc35fbed7a6cc2cee8e9aced780d6fd6ebc38c1175cd6476c0598192

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
